export const projects = [
    {
        id: 1,
        name: '自作アプリ',
        description: '動画学習管理アプリを作成しました。',
        githubUrl: 'https://github.com/NobuhiroMishima/myLearning.git',
        topicImage: '../../assets/projects/topicImage/card_MyLearning.png',
        screenImage: '../../assets/projects/screenImage/screen_MyLearning.png',
        detailImage: '../../assets/projects/detailImage/detail_MyLearning.png',
        url: 'https://mylearning-yq4s.onrender.com/',
        overview: 'JavaScriptベース・テクノロジーのMERNスタックを使用したアプリケーションを開発しました。動画学習した内容の登録・参照・削除・更新の基本機能に加え、ダッシュボード機能や無限スクロール機能を実装しました。',
        content: 'Webアプリ / CSS3コーディング / レスポンシブコーディング / 無限スクロール / ダッシュボード / MongoDB / Express / React / Node.js',
        category: 'Development',
        tag: ['エンジニア', 'webアプリ「MyLearning」', '無限スクロール', 'JavaScript', 'React', 'Node.js', 'MongoDB']
    },
    {
        id: 2,
        name: '株式会社Let’s SNS',
        description: 'コーポレートサイトの実装を担当しました。',
        githubUrl: '',
        topicImage: '../../assets/projects/topicImage/topicImage-2.jpg',
        screenImage: '',
        detailImage: '',
        url: '',
        overview: '',
        content: '',
        category: 'Development',
        tag: ['エンジニア', 'コーポレートサイト', 'お問い合わせフォーム', 'WordPress']
    },
    {
        id: 3,
        name: '株式会社エイジングケアパートナー',
        description: 'スキンケア商品のバナーを作成しました。',
        githubUrl: '',
        topicImage: '../../assets/projects/topicImage/topicImage-3.jpg',
        screenImage: '',
        detailImage: '',
        url: '',
        overview: '',
        content: '',
        category: 'Design',
        tag: ['デザイン', 'バナー', 'Figma']
    },
    {
        id: 4,
        name: '株式会社うぇぶたろう',
        description: '採用Webページの実装を担当しました。',
        githubUrl: '',
        topicImage: '../../assets/projects/topicImage/topicImage-4.jpg',
        screenImage: '',
        detailImage: '',
        url: '',
        overview: '',
        content: '',
        category: 'Development',
        tag: ['エンジニア', '採用Webサイト', 'インタビューページ', 'WordPress']
    },
    {
        id: 5,
        name: 'DATING株式会社',
        description: 'マッチングアプリの企画を担当しました。',
        githubUrl: '',
        topicImage: '../../assets/projects/topicImage/topicImage-5.jpg',
        screenImage: '',
        detailImage: '',
        url: '',
        overview: '',
        content: '',
        category: 'Planning',
        tag: ['企画', 'Webアプリ', 'マッチングアプリ「Dating」', 'GA4']
    },
    {
        id: 6,
        name: '松井なな',
        description: 'オフィシャルサイトのコーディングを担当しました。',
        githubUrl: '',
        topicImage: '../../assets/projects/topicImage/topicImage-6.jpg',
        screenImage: '',
        detailImage: '',
        url: '',
        overview: '',
        content: '',
        category: 'Development',
        tag: ['エンジニア', 'オフィシャルサイト', 'HTML', 'CSS', 'JavaScript', 'jQuery']
    },
    {
        id: 7,
        name: '雪の華リゾート',
        description: '温泉旅館のホームページのコーディングを担当しました。',
        githubUrl: '',
        topicImage: '../../assets/projects/topicImage/topicImage-7.jpg',
        screenImage: '',
        detailImage: '',
        url: '',
        overview: '',
        content: '',
        category: 'Development',
        tag: ['エンジニア', 'ホームページ', 'Web制作', 'HTML', 'CSS', 'JavaScript', 'jQuery']
    },
    {
        id: 8,
        name: '中矢 一輝',
        description: 'フォトグラファーのポートフォリオサイトのコーディングを担当しました。',
        githubUrl: '',
        topicImage: '../../assets/projects/topicImage/topicImage-8.jpg',
        screenImage: '',
        detailImage: '',
        category: 'Development',
        tag: ['エンジニア', 'ホームページ', 'Web制作', 'HTML', 'CSS', 'JavaScript', 'jQuery']
    },
]